theme: jekyll-theme-cayman
title: User Guide of Component Diagram for Versed User
description: Interpreting a component diagram of a online shopping system to see how component diagram can illustrate a system very clearly.
